AllCops:
  Exclude:
    - .bundle/**/*
    - vendor/**/*
  NewCops: enable


# reek disagrees, and complains about uncommunicative variable name
Naming/RescuedExceptionsVariableName:
  Enabled: false


Naming/MethodParameterName:
  Enabled: false


Style/HashSyntax:
  Exclude:
    - Rakefile


Style/AccessModifierDeclarations:
  Enabled: false


Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - Rakefile

Metrics/LineLength:
  Max: 120
