AllCops:
  Exclude:
    - .bundle


# reek disagrees, and complains about uncommunicative variable name
Naming/RescuedExceptionsVariableName:
  Enabled: false


Naming/UncommunicativeMethodParamName:
  Enabled: false


Style/HashSyntax:
  Exclude:
    - Rakefile


Style/AccessModifierDeclarations:
  Enabled: false


Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
